apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie
        name: mealie
        volumeMounts:
          - name: tarsoly
            mountPath: /tarsoly
          - name: data
            mountPath: /app/data

        ports:
          - containerPort: 9000
      volumes:
      - name: tarsoly
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: mealie-data

